name: "build and push connector to S3 and dev tennant"

env: 
  JIRA_PROJECT: "DEVREL"
  JIRA_COMPONENT: "Connectivity"
  SLACK_CHANNEL: "#devrel-engineering"
  CONNECTOR_NAME: "conn-discourse"


  SAIL_BASEURL: ${{ secrets.CONN_SAIL_BASEURL }}
  SAIL_TOKENURL: ${{ secrets.CONN_SAIL_TOKENURL }}
  SAIL_CLIENTID: ${{ secrets.CONN_SAIL_CLIENTID }}
  SAIL_CLIENTSECRET: ${{ secrets.CONN_SAIL_CLIENTSECRET }}

  CONNECTOR_ALIAS: "DiscourseConnector"

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build_connector:
    name: Build the connector
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Run npm install and build connector
        id: buildConnector
        run: |
          npm install
          npm run pack-zip