name: "build and push connector to S3 and dev tennant"

env: 
  JIRA_PROJECT: "DEVREL"
  JIRA_COMPONENT: "Connectivity"
  SLACK_CHANNEL: "#devrel-engineering"
  CONNECTOR_NAME: "conn-discourse"


  SAIL_BASEURL: ${{ secrets.CONN_SAIL_BASEURL }}
  SAIL_TOKENURL: ${{ secrets.CONN_SAIL_TOKENURL }}
  SAIL_CLIENTID: ${{ secrets.CONN_SAIL_CLIENTID }}
  SAIL_CLIENTSECRET: ${{ secrets.CONN_SAIL_CLIENTSECRET }}

  CONNECTOR_ALIAS: "DiscourseConnector"

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build_connector:
    name: Build the connector
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Run npm install and build connector
        id: buildConnector
        run: |
          npm install
          npm run pack-zip
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.SITE_AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.SITE_AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      # push these files to AWS
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp ./dist/discourse-connector-1.0.0.zip s3://spt-developer